import time
import json
import os

class MonteiroCryptoFormula:
    def __init__(self, database_path='permanent_server.json'):
        self.database_path = database_path
        self.knowledge_base = self._load_legacy_data()

    def _load_legacy_data(self):
        """Loads Legacy Data from the Permanent Server"""
        if os.path.exists(self.database_path):
            with open(self.database_path, 'r') as f: 
                return json.load(f)
        return {}

    def crack_key(self, n):
        # 1. MONTEIRO THEOREM: Consult Legacy Data (Permanent Server)
        if str(n) in self.knowledge_base:
            print("🧠 Key found in Permanent Server! (P = NP via Memory)")
            return self.knowledge_base[str(n)], 0.000001

        # 2. MONTEIRO THEOREM: Intelligent Filter + Calculation (New Data)
        print("⚡ New key detected. Initiating cryptographic decryption...")
        start_time = time.perf_counter()
        
        # RAM Filter: Efficient Prime Factorization
        d = 2
        temp_n = n
        factors = []
        while d * d <= temp_n:
            if temp_n % d == 0:
                factors.append(d)
                temp_n //= d
            else:
                d += 1
        if temp_n > 1: 
            factors.append(temp_n)
        
        total_time = time.perf_counter() - start_time

        # 3. Store in Permanent Server (Learning/Persistence)
        self.knowledge_base[str(n)] = factors
        with open(self.database_path, 'w') as f: 
            json.dump(self.knowledge_base, f)
        
        return factors, total_time

# --- TESTING THE MONTEIRO CRYPTOGRAPHY ---
solver = MonteiroCryptoFormula()

# Example: Number generated by two prime numbers (Simplified RSA)
secret_key = 10403 * 10607 
print(f"🔐 Key: {secret_key}")

result, duration = solver.crack_key(secret_key)
print(f"✅ Factors: {result} in {duration:.6f}s")
